version: '3.8'

services:
  noticeboard:
    image: proffapt/noticeboard
    container_name: noticeboard
    ports:
      - 8001:8001
    volumes:
      - ./assets:/usr/share/nginx/html/assets
      - ./techcoordi.json:/usr/share/nginx/html/techcoordi.json
      - ./notices:/usr/share/nginx/html/notices
      - ./nginx.conf:/etc/nginx/conf.d/default.conf